# Python CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/python:3.6.1
  working_directory: ~/andela-societies-backend

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run tests
          command: |
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - test