# Python CircleCI 2.0 configuration file

defaults: &defaults
  docker:
    - image: circleci/python:3.6.1
  working_directory: ~/andela-societies-backend

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run tests
          command: |
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  upgrade-database:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: upgrade database
          command: |
            bash scripts/upgrade.sh
      - run:
          name: Build Success
          when: on_success
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                bash scripts/slack_notification.sh "good"
            fi
      - run:
          name: Build Failed
          when: on_fail
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                bash scripts/slack_notification.sh "danger"
            fi

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: deploy application
          command: |
            bash scripts/deploy.sh
      - run:
          name: Build Success
          when: on_success
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                bash scripts/slack_notification.sh "good"
            fi
      - run:
          name: Build Failed
          when: on_fail
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                bash scripts/slack_notification.sh "danger"
            fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      # - test
      - upgrade-database:
          # requires:
          #   - test
          filters:
            branches:
              only:
                - develop
                - master
                - ft-upgrade-design-database-162630016
      # - deploy:
      #     requires:
      #       - upgrade-database
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - master
      #           - design
